spring:
  application:
    name: backend
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:sqlite:/app/data/calculator.db?date_string_format=yyyy-MM-dd}
    driver-class-name: org.sqlite.JDBC
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: false

  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources.add-mappings: false

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
  file:
    name: ${SPRING_LOGGING_FILE_NAME:/logs/backend.log}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss,Europe/Tallinn} - %msg%n"

server:
  port: 8080
  address: 0.0.0.0

  profiles:
    active: default

app:
  base-url: http://localhost:8080
  session.ttl-days: 7
